### ISSUE TITLE
Compatibility with new Kibana's version? 

### ISSUE THREAD

**Issue by ilp1995** [codingchili/kbn-authentication-plugin#15]
My Kibana version: 5.3.0

How can I to use this plugin to new versions?
Where can I edit this code to work on new version?

**Comment by codingchili** [comment]
Tested with 5.4.2, set kbnVersion in the configuration file https://github.com/codingchili/kbn-authentication-plugin/blob/master/config.json to "5.3.0".

**Comment by ilp1995** [comment]
Thank you. It's working now.

**Comment by ilp1995** [comment]
What is username and password default of users.json?

Log:

`Error: Decoding failed
    at resultHandler (/home/iverson.luis/git/kibana-dev/kbn-authentication-plugin/node_modules/argon2-ffi/lib/index.js:131:27)
    at /home/iverson.luis/git/kibana-dev/kbn-authentication-plugin/node_modules/ffi/lib/_foreign_function.js:115:9
`

`DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:71:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:88:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
`

**Comment by codingchili** [comment]
Have you tried user: username and pw: password ? cannot remember what i set the password to. You could try and generate a new password, for example using this site: https://antelle.github.io/argon2-browser/

Should probably create a commandline tool to add users, I will create an issue for that.

**Comment by ilp1995** [comment]
Thank you once again.
From file users.json the authentication was a success. Now I'm trying from ldap.

**Comment by ilp1995** [comment]
I add on config.json my ldap configurations, but apparently the authentication starts from just users.json file. Is there a way to start with ldap authentication?

**Comment by codingchili** [comment]
Yes, authentication mode is set by the storage key in the config.json file. Change from file to ldap, example "storage":"ldap".

**Comment by codingchili** [comment]
Added a new issue to improve the documentation on installing/configuring the plugin.

**Comment by ilp1995** [comment]
Thank you. Now all is working. This plugin is very good. Congratulations.

**Comment by ilp1995** [comment]
I had tried to use others plugins, for example SearchGuard e ReadonlyREST, but they are very complicated e don't provide a UI free. Once again, congratulations for your contribuitions. Now, I will to adapted this plugin for me. Thank you.

**Comment by codingchili** [comment]
Thanks for the feedback! Good to hear you got it working. If there's any problems just open a new issue.
