### ISSUE TITLE
when I install, it says wrong ELF class: ELFCLASS32"

### ISSUE THREAD

**Issue by pipamc** [codingchili/kbn-authentication-plugin#20]
my compute is:
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie
and I build with npm install --arch=ia32
what's wrong with this?
Thanks

**Comment by codingchili** [comment]
Hello! 

wrong ELF class indicates that there is a mismatch in compiler/target arch. Could you please try building with:
```
npm install
```
The --arch=ia32 command is only required for windows, as Kibana on windows only comes with 32bit nodejs. Note that building for x64 requires you to install the x64 version of Kibana.

Thanks for submitting an issue.
