### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by n0rg3** [codingchili/kbn-authentication-plugin#21]
Hi, i got this error when enter the username "Illegal instruction (core dumped)"

**Comment by codingchili** [comment]
Hello!

Interesting, have not seen this issue before. Going to need some more details to figure this one out.

- How did you build? with/without--arch=ia32 ?
- Do you build and run on the same machine?
- What does your configuration look like?
- Which environment are you running this on? 
- Kibana version?

Thanks for submitting an issue,
Regards

**Comment by codingchili** [comment]
Assuming this has something to do with the native dependency on argon2.
