### ISSUE TITLE
JSON.parse error

### ISSUE THREAD

**Issue by nugusbayevkk** [codingchili/kbn-authentication-plugin#23]
i got exception in JSON.parse(data) in file.js

server    log   [11:32:32.263] [fatal] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)

after this exception, content of users.json are cleared

**Comment by codingchili** [comment]
Hello,

Have not seen this exception before, seems like it fails to parse the users.json file. Do you get the same error if you reset the [users.json](https://github.com/codingchili/kbn-authentication-plugin/blob/master/users.json) file? could you upload your original users.json file?

has any changes been made to the users.json or config.json files?
