### ISSUE TITLE
Question - Current status

### ISSUE THREAD

**Issue by sandman137** [codingchili/kbn-authentication-plugin#3]
Hi, this is a cool project. Just wanted to check on following with you:

1. Does it work on Kibana 4.x? Is 5.0 a pre-requisite?

2. What is the current status on auth? Is 2FA is working already? 

3. Which is the stable version where basic authentication functionality is working with single user i.e. no user management is required.

**Comment by codingchili** [comment]
Hello,

1. This works with Kibana 5.0, no support at all for earlier versions as there has been changes to the plugin system. 
2. 2FA is working fine, user management is not implemented at all. This means that all dashboards are visible to all users.
3. Theres no stable version yet, the tests are passing and its working as expected. There would not be a lot of work to release one, I would just have to check that it works with the newly released stable on Kibana 5.0.

The things currently missing are the ability to configure users from configuration and to use the MongoDB server to store user passwords. For this a separate LDAP is used. The LDAP support is intended as a feature and support for relying on MongoDB for all storage should be added.

Let me know if you are interested in configuring users in the json config and/or storing users in MongoDB as an alternative to LDAP. It would be a minor thing to add and it should be present, as I also will require it further down the road in another project.

Thank you for showing interest in this project,
Regards
