### ISSUE TITLE
Error : kbn-authentication-plugin\" was disabled because it expected Kibana version \"0.1.0\", and found \"5.2.2\"."

### ISSUE THREAD

**Issue by jayannah** [codingchili/kbn-authentication-plugin#4]
please see the last line for error... i.e "kbn-authentication-plugin\" was disabled because it expected Kibana version \"0.1.0\", and found \"5.2.2\"."

why is it saying expected kibana version is 0.1.0?? as your github read me, you seems to be have tested with 5.xxx..

{"type":"log","@timestamp":"2017-04-24T18:05:48Z","tags":["plugins","debug"],"pid":25840,"dir":"/usr/share/kibana/plugins","message":"Scanning `/usr/share/kibana/plugins` for plugins"}
{"type":"log","@timestamp":"2017-04-24T18:05:48Z","tags":["plugins","debug"],"pid":25840,"dir":"/usr/share/kibana/src/core_plugins","message":"Scanning `/usr/share/kibana/src/core_plugins` for plugins"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/plugins/kbn-authentication-plugin/index.js","message":"Found plugin at /usr/share/kibana/plugins/kbn-authentication-plugin/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/console/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/console/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/elasticsearch/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/elasticsearch/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/kbn_doc_views/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/kbn_doc_views/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/kbn_vislib_vis_types/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/kbn_vislib_vis_types/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/kibana/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/kibana/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/markdown_vis/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/markdown_vis/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/metric_vis/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/metric_vis/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/spy_modes/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/spy_modes/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/status_page/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/status_page/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/table_vis/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/table_vis/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/tagcloud/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/tagcloud/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["plugins","debug"],"pid":25840,"path":"/usr/share/kibana/src/core_plugins/timelion/index.js","message":"Found plugin at /usr/share/kibana/src/core_plugins/timelion/index.js"}
{"type":"log","@timestamp":"2017-04-24T18:05:49Z","tags":["warning"],"pid":25840,"message":"Plugin \"kbn-authentication-plugin\" was disabled because it expected Kibana version \"0.1.0\", and found \"5.2.2\"."}

**Comment by codingchili** [comment]
Its tested with the 5.0.0-SNAPSHOT version, the version needs to be updated in the configuration file.
https://github.com/codingchili/kbn-authentication-plugin/blob/master/config.json#L13

Not sure why it is expecting 0.1.0, which version of kibana are you running?
